### PR TITLE
Support Member Expressions - code

### PR DESCRIPTION
**Pull request by iamcarrico**
This starts off the work to support member expressions for ticket #71. This is my first time playing with peg.js, so I would not be surprised if some of this needs to change. I will keep working on more complex expressions, but wanted to push this up so you know that I am taking a stab for yah.

### CODE REVIEW

**Comment by iamcarrico** [comment]
I changed some things with how Peg.js evaluates numbers (so a negative will be included). I also added in some code for the ranges. Currently the only tests failing are the ones that I added that because of the current way I am making the ranges, are failing. 

We need a new way of making these ranges, outside of the Node.toListNode() I am using now. I see it has the limitation of those lists that we are specifying cannot be made. No matter-- it is just the next things that needs to happen.

**Comment by curvedmark** [comment]
Wow, thank you for taking the time writing this.

I will incorporate your code but probably not by merging this. Because the commits are messed up actually (a previous version of grammar is used in d9581f3, and is manually reverted back in cdd6c99), also the grammar inside square brackets should just be range, which is a superset of unaryExpression that handles negative numbers, which in turn is a superset of number. There should also be no optional spaces between the variable and `[` (to be consistent with call).

Anyway, thanks. :)

**Comment by iamcarrico** [comment]
Rodger! Yeah, I am not sure what caused the weirdness with the commits in there, but I had to re-build my local repo to get it right again. I can update the code to use unaryExpression if you want--- as I said I was just taking a stab to get into the code. Here to help where I can. 

(btw--- if you can, merge in ff1ce08 --- so the node_modules folder doesn't get added in accidentally... and add a new line at the end of the file)

**Comment by curvedmark** [comment]
node_modules should be in the global gitignore (you should never commit node_modules, rely on package.json instead). I use [github gitignore](https://github.com/github/gitignore/) for my global gitignore.

**Comment by iamcarrico** [comment]
node_modules shouldn't be in a global gitignore file, and that repo specifies that. Those gitignore files are meant as templates for projects--- and system/editor preferences that will span an entire computer should be in the global file. This is even specified on the repo your linked to.

Why: It is not inconceivable that another project, in another language, with another purpose could have a folder called node_modules. Shit--- I could have a folder named that in a Drupal project easy. 

Solution: #73

**Pull request closed without merging**
