### PR TITLE
Add in opposite_position fucntion

### PR DESCRIPTION
**Pull request by iamcarrico**
This adds in a function called $opposite_position() that will return the opposite postions.

So $opposite_position(left) will be right, $opposite_position(top) is bottom, so on.

### CODE REVIEW

**Comment by iamcarrico** [comment]
I shall do that--- I actually had that there first but the file name didn't like it, so I switched it all. I will put the function to where it started. 

And I will handle it, no prob.

**Comment by iamcarrico** [comment]
Okay, added in the ability for list nodes to be used. 

I cannot have the name be opposite-position, because the js object cannot have '-', from what I can tell. We can either leave it how it is, or move it to "oppositePosition".

**Comment by iamcarrico** [comment]
I just made it camel case... because I like it that way.

**Comment by iamcarrico** [comment]
btw--- Fixed the minor Travis issue. This is what I get for doing PHP too....

Ready when you are @curvedmark

**Comment by curvedmark** [comment]
merged, thanks. I renamed it to `opp`.

**Pull request merged**
